### ISSUE TITLE
Comma after "do" token is swallowed

### ISSUE THREAD

**Issue by I-Al-Istannen** [iComputerfreak/DerCompiler#3]
Currently your code swallows the next token after `do` if it is not part of an identifier.

I'd guess it happens as you try to read the `o` in `do` twice:
```java
                    case 'o':
                        readCharacter();
                        // do. | do.uble
                        if (!isIdentifierChar(currentChar)) {
                            readCharacter();                                // <---- Duplicated read here
                            return Token.DO;
                        } else return compareSuffix(Token.DOUBLE_TYPE, 2);
```

In the mjtest repo this triggers for `do, else` which your compiler turns into `do` and `else` tokens, swallowing the comma.

I wouldn't normally report random bugs in your compiler but I found that in the pipeline output and was intrigued. I hope that's alright with you :)

**Comment by robinmaisch** [comment]
Very much appreciated, thanks! Spot on with the analysis.
